# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-28 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20191028_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='singer_mobil',
            new_name='signer_mobil',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='singer_name',
            new_name='signer_name',
        ),
    ]
