# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-30 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20191028_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='signer_mobil',
            new_name='signer_mobile',
        ),
    ]
