# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20191028_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_amount',
            field=models.FloatField(default=0, verbose_name='订单金额'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='购买数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='订单信息'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_FINISHED', '交易完结'), ('TRADE_CLOSED', '交易关闭'), ('WAIT_BUYER_PAY', '待支付'), ('TRADE_SUCCESS', '交易成功'), ('TRADE_CREATED', '交易创建')], default='WAIT_BUYER_PAY', max_length=20, verbose_name='支付状态'),
        ),
    ]
