# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-30 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20191030_1616'),
    ]
