# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-31 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20191030_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_mobil',
            new_name='signer_mobile',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order_mount',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='num',
        ),
    ]
