# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-31 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191031_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodscategorybrand',
            old_name='imag',
            new_name='image',
        ),
    ]
